alert("Hello")
alert("I am god")
alert("I always observe human deeds")
alert("It is good Weather")
alert("but human deeds is bat")
alert("やあ")
alert("私はニオ")
alert("このサイトの制作者だ")
alert("おっと、気に入らないからってエンターを連打するなよ？")
alert("人の話はよく聞くものだ。")
alert("...偉そうに言える人間じゃないが。")
alert("さて、見てのとおり、初心者だ。")
alert("...見るべきはサイトだぞ。")
alert("HTML、JS、CSSを用いて作っている")
alert("ああ、そうだ。")
alert("好きな数字はあるかい？")
alert("私は17が好きだ。")
alert("...君は違ったりするかい？")
alert("そりゃそうだろう。")
alert("人間は違うからこそ輝くものだ。")
alert("巷では666は禁忌とされていたな。")
alert("私は17だけでなく、666、13、4も好きだぞ。")
alert("そういえば、好きな馬はいるかい？")
alert("私はディープインパクトが好きだ。")
alert("最近の馬だったらイクイノックスだな。")
alert("突然だが、htmlでfpsを作ろうと思っているんだが、")
alert("作り方がどうもわからなくてねぇ。")
alert("Canvasの使い方を知らないかい？")
